In [1]:
import numpy as np
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.1.0

In [2]:
marks = pd.Series([85, 92, 78, 88])

print(marks)
print(marks.values)
print(marks.index)
print(marks.dtype)
print(marks.shape)

0    85
1    92
2    78
3    88
dtype: int64
[85 92 78 88]
RangeIndex(start=0, stop=4, step=1)
int64
(4,)

In [3]:
marks = pd.Series(
    [85, 92, 78],
    index=["Siddu", "Rahul", "Priya"],
    name="Marks"
)

print(marks)
print(marks["Rahul"])  # 92

Siddu    85
Rahul    92
Priya    78
Name: Marks, dtype: int64
92

In [4]:
print(marks.mean())
print(marks.max())
print(marks.min())
print(marks.sort_values(ascending=False))

85.0
92
78
Rahul    92
Siddu    85
Priya    78
Name: Marks, dtype: int64

In [7]:
df = pd.DataFrame({
    "Name": ["Asha", "Rahul", "Priya", "Kiran", "Arjun"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 92, 78, 88, 95],
    "Department": ["CSE", "ECE", "CSE", "IT", "ECE"]
})

df

    Name  Age  Marks Department
0   Asha   20     85        CSE
1  Rahul   21     92        ECE
2  Priya   19     78        CSE
3  Kiran   22     88         IT
4  Arjun   20     95        ECE

In [8]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.info())
print(df.describe())
print(df.head(3))
print(df.tail(2))

(5, 4)
Index(['Name', 'Age', 'Marks', 'Department'], dtype='str')
RangeIndex(start=0, stop=5, step=1)
Name            str
Age           int64
Marks         int64
Department      str
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Marks       5 non-null      int64
 3   Department  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes
None
             Age      Marks
count   5.000000   5.000000
mean   20.400000  87.600000
std     1.140175   6.580274
min    19.000000  78.000000
25%    20.000000  85.000000
50%    20.000000  88.000000
75%    21.000000  92.000000
max    22.000000  95.000000
    Name  Age  Marks Department
0   Asha   20     85        CSE
1  Rahul   21     92        ECE
2  Priya   19     78        CSE
    Name  Age  Marks Department
3  Kiran   22     88         IT
4  Arjun   20     95        ECE

In [9]:
X = np.array([
    [18, 85],
    [20, 92],
    [19, 78],
    [22, 88]
])

df = pd.DataFrame(
    X,
    columns=["Age", "Marks"]
)

print(df)

   Age  Marks
0   18     85
1   20     92
2   19     78
3   22     88

In [10]:
X = df.to_numpy()

print(X)
print(X.shape)

[[18 85]
 [20 92]
 [19 78]
 [22 88]]
(4, 2)

In [11]:
print(df["Marks"])

0    85
1    92
2    78
3    88
Name: Marks, dtype: int64

In [12]:
print(df[["Age", "Marks"]])

   Age  Marks
0   18     85
1   20     92
2   19     78
3   22     88

In [13]:
print(df.iloc[0])       # First row
print(df.iloc[0:3])     # First three rows
print(df.iloc[1, 1])    # Second row, second column

Age      18
Marks    85
Name: 0, dtype: int64
   Age  Marks
0   18     85
1   20     92
2   19     78
92

In [14]:
df.index = ["S1", "S2", "S3", "S4"]

print(df.loc["S1"])
print(df.loc["S2":"S4"])

Age      18
Marks    85
Name: S1, dtype: int64
    Age  Marks
S2   20     92
S3   19     78
S4   22     88

In [15]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Asha", "Rahul", "Priya", "Kiran", "Arjun"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 92, 78, 88, 95],
    "Department": ["CSE", "ECE", "CSE", "IT", "ECE"]
})

print("Dataset shape:", df.shape)
print("Average marks:", df["Marks"].mean())
print("Highest marks:", df["Marks"].max())
print("Student with highest marks:")
print(df.loc[df["Marks"].idxmax()])

print("Only CSE students:")
print(df.loc[df["Department"] == "CSE"])

Dataset shape: (5, 4)
Average marks: 87.6
Highest marks: 95
Student with highest marks:
Name          Arjun
Age              20
Marks            95
Department      ECE
Name: 4, dtype: object
Only CSE students:
    Name  Age  Marks Department
0   Asha   20     85        CSE
2  Priya   19     78        CSE

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/customers.csv")

print(df.head())

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
3         104   NaN  Hyderabad      450000.0             80     Silver
4         105  42.0     Mumbai     1200000.0             35       Gold

In [2]:
# Load only the first 5 rows
sample = pd.read_csv("../data/raw/customers.csv", nrows=5)

# Load only selected columns
subset = pd.read_csv(
    "../data/raw/customers.csv",
    usecols=["CustomerID", "Age", "AnnualIncome"]
)

# Read a CSV with a different delimiter
# df = pd.read_csv("file.csv", sep=";")

In [3]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data types:\n", df.dtypes)

print("\nFirst 5 rows:")
print(df.head())

print("\nLast 5 rows:")
print(df.tail())

print("\nDataset information:")
df.info()

print("\nStatistical summary:")
print(df.describe())

Shape: (10, 6)
Columns: ['CustomerID', 'Age', 'City', 'AnnualIncome', 'SpendingScore', 'Membership']
Data types:
 CustomerID         int64
Age              float64
City                 str
AnnualIncome     float64
SpendingScore      int64
Membership           str
dtype: object

First 5 rows:
   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
3         104   NaN  Hyderabad      450000.0             80     Silver
4         105  42.0     Mumbai     1200000.0             35       Gold

Last 5 rows:
   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
5         106  30.0  Bengaluru           NaN             65     Silver
6         107  25.0    Chennai      500000.0             90       Gold
7         108  38.0     Mumbai      950000.0             40     Silver
8         109  29.0  Hyderabad      550000.0             70       Gold
9         110  45.0  Bengaluru     1500000.0             25     Silver

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     10 non-null     int64
 1   Age            9 non-null      float64
 2   City           10 non-null     str
 3   AnnualIncome   9 non-null      float64
 4   SpendingScore  10 non-null     int64
 5   Membership     10 non-null     str
dtypes: float64(2), int64(2), str(2)
memory usage: 612.0 bytes

Statistical summary:
       CustomerID        Age  AnnualIncome  SpendingScore
count    10.00000   9.000000  9.000000e+00      10.000000
mean    105.50000  32.666667  7.666667e+05      58.500000
std       3.02765   7.810250  3.840573e+05      21.350254
min     101.00000  22.000000  3.500000e+05      25.000000
25%     103.25000  28.000000  5.000000e+05      41.250000
50%     105.50000  30.000000  6.000000e+05      62.500000
75%     107.75000  38.000000  9.500000e+05      73.750000
max     110.00000  45.000000  1.500000e+06      90.000000

In [4]:
# Missing-value count for each column
print(df.isnull().sum())

# Missing-value percentage for each column
missing_percentage = df.isnull().mean() * 100
print(missing_percentage)

# Total missing cells
print("Total missing cells:", df.isnull().sum().sum())

CustomerID       0
Age              1
City             0
AnnualIncome     1
SpendingScore    0
Membership       0
dtype: int64
CustomerID        0.0
Age              10.0
City              0.0
AnnualIncome     10.0
SpendingScore     0.0
Membership        0.0
dtype: float64
Total missing cells: 2

In [7]:
missing_rows = df[df.isnull().any(axis=1)]
missing_rows

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
3         104   NaN  Hyderabad      450000.0             80     Silver
5         106  30.0  Bengaluru           NaN             65     Silver

In [8]:
numerical_columns = df.select_dtypes(include="number").columns
categorical_columns = df.select_dtypes(include=["object", "category"]).columns

print("Numerical columns:", numerical_columns.tolist())
print("Categorical columns:", categorical_columns.tolist())

Numerical columns: ['CustomerID', 'Age', 'AnnualIncome', 'SpendingScore']
Categorical columns: ['City', 'Membership']

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_37828\3057177594.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object", "category"]).columns

In [9]:
# Count complete duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Check unique values
print("Unique cities:", df["City"].unique())
print("Membership types:", df["Membership"].unique())

# Check numerical ranges
print(df[["Age", "AnnualIncome", "SpendingScore"]].describe())

Duplicate rows: 0
Unique cities: <StringArray>
['Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai']
Length: 4, dtype: str
Membership types: <StringArray>
['Gold', 'Silver']
Length: 2, dtype: str
             Age  AnnualIncome  SpendingScore
count   9.000000  9.000000e+00      10.000000
mean   32.666667  7.666667e+05      58.500000
std     7.810250  3.840573e+05      21.350254
min    22.000000  3.500000e+05      25.000000
25%    28.000000  5.000000e+05      41.250000
50%    30.000000  6.000000e+05      62.500000
75%    38.000000  9.500000e+05      73.750000
max    45.000000  1.500000e+06      90.000000

In [10]:
invalid_age = df[(df["Age"] < 0) | (df["Age"] > 120)]

invalid_income = df[df["AnnualIncome"] < 0]

invalid_score = df[
    (df["SpendingScore"] < 0) |
    (df["SpendingScore"] > 100)
]

print("Invalid ages:\n", invalid_age)
print("Invalid incomes:\n", invalid_income)
print("Invalid scores:\n", invalid_score)

Invalid ages:
 Empty DataFrame
Columns: [CustomerID, Age, City, AnnualIncome, SpendingScore, Membership]
Index: []
Invalid incomes:
 Empty DataFrame
Columns: [CustomerID, Age, City, AnnualIncome, SpendingScore, Membership]
Index: []
Invalid scores:
 Empty DataFrame
Columns: [CustomerID, Age, City, AnnualIncome, SpendingScore, Membership]
Index: []

In [11]:
def inspect_dataset(df):
    print("=" * 45)
    print("DATASET INSPECTION REPORT")
    print("=" * 45)

    print(f"\nRows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")

    print("\nColumn data types:")
    print(df.dtypes)

    print("\nMissing values:")
    print(df.isnull().sum())

    print("\nMissing percentages:")
    print((df.isnull().mean() * 100).round(2))

    print("\nDuplicate rows:", df.duplicated().sum())

    print("\nNumerical summary:")
    print(df.describe())

    print("\nCategorical summary:")
    print(df.describe(include="object"))


inspect_dataset(df)

=============================================
DATASET INSPECTION REPORT
=============================================

Rows: 10
Columns: 6

Column data types:
CustomerID         int64
Age              float64
City                 str
AnnualIncome     float64
SpendingScore      int64
Membership           str
dtype: object

Missing values:
CustomerID       0
Age              1
City             0
AnnualIncome     1
SpendingScore    0
Membership       0
dtype: int64

Missing percentages:
CustomerID        0.0
Age              10.0
City              0.0
AnnualIncome     10.0
SpendingScore     0.0
Membership        0.0
dtype: float64

Duplicate rows: 0

Numerical summary:
       CustomerID        Age  AnnualIncome  SpendingScore
count    10.00000   9.000000  9.000000e+00      10.000000
mean    105.50000  32.666667  7.666667e+05      58.500000
std       3.02765   7.810250  3.840573e+05      21.350254
min     101.00000  22.000000  3.500000e+05      25.000000
25%     103.25000  28.000000  5.000000e+05      41.250000
50%     105.50000  30.000000  6.000000e+05      62.500000
75%     107.75000  38.000000  9.500000e+05      73.750000
max     110.00000  45.000000  1.500000e+06      90.000000

Categorical summary:
             City Membership
count          10         10
unique          4          2
top     Hyderabad       Gold
freq            3          5

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_37828\783270516.py:24: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include="object"))

In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/customers.csv")

print(df.head())

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
3         104   NaN  Hyderabad      450000.0             80     Silver
4         105  42.0     Mumbai     1200000.0             35       Gold

In [13]:
# Select one column — returns a Series
ages = df["Age"]

# Select multiple columns — returns a DataFrame
features = df[["Age", "AnnualIncome", "SpendingScore"]]

print(type(ages))
print(type(features))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [14]:
X = df[["Age", "AnnualIncome", "SpendingScore"]]

print(X.shape)

(10, 3)

In [15]:
# First row by position
print(df.iloc[0])

# First three rows
print(df.iloc[:3])

# Rows 0–2, columns Age and City
print(df.loc[0:2, ["Age", "City"]])

# Second row, third column by position
print(df.iloc[1, 2])

CustomerID             101
Age                   22.0
City             Hyderabad
AnnualIncome      350000.0
SpendingScore           75
Membership            Gold
Name: 0, dtype: object
   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
    Age       City
0  22.0  Hyderabad
1  28.0  Bengaluru
2  35.0    Chennai
Bengaluru

In [16]:
indexed_df = df.set_index("CustomerID")

print(indexed_df.loc[101])
print(indexed_df.loc[[101, 105, 109]])
indexed_df

Age                   22.0
City             Hyderabad
AnnualIncome      350000.0
SpendingScore           75
Membership            Gold
Name: 101, dtype: object
             Age       City  AnnualIncome  SpendingScore Membership
CustomerID
101         22.0  Hyderabad      350000.0             75       Gold
105         42.0     Mumbai     1200000.0             35       Gold
109         29.0  Hyderabad      550000.0             70       Gold

             Age       City  AnnualIncome  SpendingScore Membership
CustomerID
101         22.0  Hyderabad      350000.0             75       Gold
102         28.0  Bengaluru      600000.0             60     Silver
103         35.0    Chennai      800000.0             45       Gold
104          NaN  Hyderabad      450000.0             80     Silver
105         42.0     Mumbai     1200000.0             35       Gold
106         30.0  Bengaluru           NaN             65     Silver
107         25.0    Chennai      500000.0             90       Gold
108         38.0     Mumbai      950000.0             40     Silver
109         29.0  Hyderabad      550000.0             70       Gold
110         45.0  Bengaluru     1500000.0             25     Silver

In [17]:
older_customers = df[df["Age"] > 30]

print(older_customers)

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
2         103  35.0    Chennai      800000.0             45       Gold
4         105  42.0     Mumbai     1200000.0             35       Gold
7         108  38.0     Mumbai      950000.0             40     Silver
9         110  45.0  Bengaluru     1500000.0             25     Silver

In [18]:
df[df["AnnualIncome"] >= 800000]
df[df["SpendingScore"] < 50]
df[df["City"] == "Hyderabad"]
df[df["Membership"] == "Gold"]

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
2         103  35.0    Chennai      800000.0             45       Gold
4         105  42.0     Mumbai     1200000.0             35       Gold
6         107  25.0    Chennai      500000.0             90       Gold
8         109  29.0  Hyderabad      550000.0             70       Gold

In [19]:
# Customers older than 25 AND spending score above 60
result = df[
    (df["Age"] > 25) &
    (df["SpendingScore"] > 60)
]

print(result)

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
5         106  30.0  Bengaluru           NaN             65     Silver
8         109  29.0  Hyderabad      550000.0             70       Gold

In [20]:
cities = ["Hyderabad", "Bengaluru"]

result = df[df["City"].isin(cities)]

print(result)

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
3         104   NaN  Hyderabad      450000.0             80     Silver
5         106  30.0  Bengaluru           NaN             65     Silver
8         109  29.0  Hyderabad      550000.0             70       Gold
9         110  45.0  Bengaluru     1500000.0             25     Silver

In [27]:
missing_age = df[df["Age"].isna()]

known_age = df[df["Age"].notna()]

display(
    known_age,
    missing_age
)

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
4         105  42.0     Mumbai     1200000.0             35       Gold
5         106  30.0  Bengaluru           NaN             65     Silver
6         107  25.0    Chennai      500000.0             90       Gold
7         108  38.0     Mumbai      950000.0             40     Silver
8         109  29.0  Hyderabad      550000.0             70       Gold
9         110  45.0  Bengaluru     1500000.0             25     Silver

   CustomerID  Age       City  AnnualIncome  SpendingScore Membership
3         104  NaN  Hyderabad      450000.0             80     Silver

In [28]:
# Highest spending score first
print(df.sort_values("SpendingScore", ascending=False))

# Lowest income first
print(df.sort_values("AnnualIncome", ascending=True))

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
6         107  25.0    Chennai      500000.0             90       Gold
3         104   NaN  Hyderabad      450000.0             80     Silver
0         101  22.0  Hyderabad      350000.0             75       Gold
8         109  29.0  Hyderabad      550000.0             70       Gold
5         106  30.0  Bengaluru           NaN             65     Silver
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
7         108  38.0     Mumbai      950000.0             40     Silver
4         105  42.0     Mumbai     1200000.0             35       Gold
9         110  45.0  Bengaluru     1500000.0             25     Silver
   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
3         104   NaN  Hyderabad      450000.0             80     Silver
6         107  25.0    Chennai      500000.0             90       Gold
8         109  29.0  Hyderabad      550000.0             70       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
7         108  38.0     Mumbai      950000.0             40     Silver
4         105  42.0     Mumbai     1200000.0             35       Gold
9         110  45.0  Bengaluru     1500000.0             25     Silver
5         106  30.0  Bengaluru           NaN             65     Silver

In [29]:
result = df.sort_values(
    by=["City", "AnnualIncome"],
    ascending=[True, False]
)

print(result)

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
9         110  45.0  Bengaluru     1500000.0             25     Silver
1         102  28.0  Bengaluru      600000.0             60     Silver
5         106  30.0  Bengaluru           NaN             65     Silver
2         103  35.0    Chennai      800000.0             45       Gold
6         107  25.0    Chennai      500000.0             90       Gold
8         109  29.0  Hyderabad      550000.0             70       Gold
3         104   NaN  Hyderabad      450000.0             80     Silver
0         101  22.0  Hyderabad      350000.0             75       Gold
4         105  42.0     Mumbai     1200000.0             35       Gold
7         108  38.0     Mumbai      950000.0             40     Silver

In [30]:
top_customers = df.nlargest(3, "SpendingScore")

print(top_customers)

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
6         107  25.0    Chennai      500000.0             90       Gold
3         104   NaN  Hyderabad      450000.0             80     Silver
0         101  22.0  Hyderabad      350000.0             75       Gold

In [31]:
# Check membership in a list
print(df[df["City"].isin(["Mumbai", "Chennai"])])

# Search text
print(df[df["City"].str.contains("pur", case=False, na=False)])

# Filter using query syntax
print(df.query("Age > 25 and SpendingScore >= 60"))

   CustomerID   Age     City  AnnualIncome  SpendingScore Membership
2         103  35.0  Chennai      800000.0             45       Gold
4         105  42.0   Mumbai     1200000.0             35       Gold
6         107  25.0  Chennai      500000.0             90       Gold
7         108  38.0   Mumbai      950000.0             40     Silver
Empty DataFrame
Columns: [CustomerID, Age, City, AnnualIncome, SpendingScore, Membership]
Index: []
   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
1         102  28.0  Bengaluru      600000.0             60     Silver
5         106  30.0  Bengaluru           NaN             65     Silver
8         109  29.0  Hyderabad      550000.0             70       Gold

In [32]:
good_customers = df[
    (df["AnnualIncome"]>=500000) &
    (df["SpendingScore"]>=60) &
    (df["Age"].notna())
]

good_customers = good_customers.sort_values(
    "SpendingScore" ,
    ascending = False
)

good_customers

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
6         107  25.0    Chennai      500000.0             90       Gold
8         109  29.0  Hyderabad      550000.0             70       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver