In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/customers.csv")

df["Age"] = df["Age"].fillna(df["Age"].median())

df["AnnualIncome"] = df["AnnualIncome"].fillna(
    df["AnnualIncome"].median()
)

print(df.head())

   CustomerID   Age       City  AnnualIncome  SpendingScore Membership
0         101  22.0  Hyderabad      350000.0             75       Gold
1         102  28.0  Bengaluru      600000.0             60     Silver
2         103  35.0    Chennai      800000.0             45       Gold
3         104  30.0  Hyderabad      450000.0             80     Silver
4         105  42.0     Mumbai     1200000.0             35       Gold

In [2]:
city_spending = df.groupby("City")["SpendingScore"].mean()

city_spending

City
Bengaluru    50.0
Chennai      67.5
Hyderabad    75.0
Mumbai       37.5
Name: SpendingScore, dtype: float64

In [3]:
city_spending = (
    df.groupby("City", as_index=False)["SpendingScore"]
      .mean()
)

print(city_spending)

        City  SpendingScore
0  Bengaluru           50.0
1    Chennai           67.5
2  Hyderabad           75.0
3     Mumbai           37.5

In [10]:
summary = df.groupby("City").agg(
    Customer_Count=("CustomerID", "count"),
    Average_Age=("Age", "mean"),
    Average_Income=("AnnualIncome", "mean"),
    Average_Spending=("SpendingScore", "mean"),
    Maximum_Spending=("SpendingScore", "max")
)

summary

,Customer_Count,Average_Age,Average_Income,Average_Spending,Maximum_Spending
City,,,,,
Bengaluru,3,34.333333,900000.0,50.0,65
Chennai,2,30.000000,650000.0,67.5,90
Hyderabad,3,27.000000,450000.0,75.0,80
Mumbai,2,40.000000,1075000.0,37.5,40

In [11]:
result = df.groupby(
    ["City", "Membership"],
    as_index=False
).agg(
    Customers=("CustomerID", "count"),
    Average_Income=("AnnualIncome", "mean"),
    Average_Spending=("SpendingScore", "mean")
)

print(result.round(2))

        City Membership  Customers  Average_Income  Average_Spending
0  Bengaluru     Silver          3        900000.0              50.0
1    Chennai       Gold          2        650000.0              67.5
2  Hyderabad       Gold          2        450000.0              72.5
3  Hyderabad     Silver          1        450000.0              80.0
4     Mumbai       Gold          1       1200000.0              35.0
5     Mumbai     Silver          1        950000.0              40.0

In [12]:
pivot = pd.pivot_table(
    df,
    values="SpendingScore",
    index="City",
    columns="Membership",
    aggfunc="mean"
)

print(pivot.round(2))

Membership  Gold  Silver
City
Bengaluru    NaN    50.0
Chennai     67.5     NaN
Hyderabad   72.5    80.0
Mumbai      35.0    40.0

In [13]:
counts = pd.crosstab(
    df["City"],
    df["Membership"]
)

print(counts)

Membership  Gold  Silver
City
Bengaluru      0       3
Chennai        2       0
Hyderabad      2       1
Mumbai         1       1

In [14]:
city_summary = df.groupby(
    "City",
    as_index=False
).agg(
    Average_Spending=("SpendingScore", "mean"),
    Customer_Count=("CustomerID", "count")
)


city_summary = city_summary.sort_values(
    "Average_Spending",
    ascending=False
)

print(city_summary)

        City  Average_Spending  Customer_Count
2  Hyderabad              75.0               3
1    Chennai              67.5               2
0  Bengaluru              50.0               3
3     Mumbai              37.5               2

In [16]:
df["City_Average_Income"] = (
    df.groupby("City")["AnnualIncome"]
      .transform("mean")
)

df["Income_vs_City_Average"] = (
    df["AnnualIncome"] - df["City_Average_Income"]
)

print(
    df[
        [
            "CustomerID",
            "City",
            "AnnualIncome",
            "City_Average_Income",
            "Income_vs_City_Average"
        ]
    ]
)
df

   CustomerID       City  AnnualIncome  City_Average_Income  \
0         101  Hyderabad      350000.0             450000.0
1         102  Bengaluru      600000.0             900000.0
2         103    Chennai      800000.0             650000.0
3         104  Hyderabad      450000.0             450000.0
4         105     Mumbai     1200000.0            1075000.0
5         106  Bengaluru      600000.0             900000.0
6         107    Chennai      500000.0             650000.0
7         108     Mumbai      950000.0            1075000.0
8         109  Hyderabad      550000.0             450000.0
9         110  Bengaluru     1500000.0             900000.0

   Income_vs_City_Average
0               -100000.0
1               -300000.0
2                150000.0
3                     0.0
4                125000.0
5               -300000.0
6               -150000.0
7               -125000.0
8                100000.0
9                600000.0

,CustomerID,Age,City,AnnualIncome,SpendingScore,Membership,City_Average_Income,Income_vs_City_Average
0,101,22.0,Hyderabad,350000.0,75,Gold,450000.0,-100000.0
1,102,28.0,Bengaluru,600000.0,60,Silver,900000.0,-300000.0
2,103,35.0,Chennai,800000.0,45,Gold,650000.0,150000.0
3,104,30.0,Hyderabad,450000.0,80,Silver,450000.0,0.0
4,105,42.0,Mumbai,1200000.0,35,Gold,1075000.0,125000.0
5,106,30.0,Bengaluru,600000.0,65,Silver,900000.0,-300000.0
6,107,25.0,Chennai,500000.0,90,Gold,650000.0,-150000.0
7,108,38.0,Mumbai,950000.0,40,Silver,1075000.0,-125000.0
8,109,29.0,Hyderabad,550000.0,70,Gold,450000.0,100000.0
9,110,45.0,Bengaluru,1500000.0,25,Silver,900000.0,600000.0

In [17]:
import pandas as pd
import numpy as np

customers = pd.DataFrame({
    "CustomerID": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rahul", "Priya", "Kiran", "Arjun"],
    "City": ["Hyderabad", "Bengaluru", "Chennai", "Mumbai", "Hyderabad"]
})

transactions = pd.DataFrame({
    "TransactionID": [1, 2, 3, 4, 5, 6],
    "CustomerID": [101, 102, 101, 103, 106, 105],
    "Amount": [1200, 2500, 800, 3200, 1500, 4000]
})

print(customers)
print(transactions)

   CustomerID   Name       City
0         101   Asha  Hyderabad
1         102  Rahul  Bengaluru
2         103  Priya    Chennai
3         104  Kiran     Mumbai
4         105  Arjun  Hyderabad
   TransactionID  CustomerID  Amount
0              1         101    1200
1              2         102    2500
2              3         101     800
3              4         103    3200
4              5         106    1500
5              6         105    4000

In [18]:
inner = pd.merge(
    customers,
    transactions,
    on="CustomerID",
    how="inner"
)

print(inner)

   CustomerID   Name       City  TransactionID  Amount
0         101   Asha  Hyderabad              1    1200
1         101   Asha  Hyderabad              3     800
2         102  Rahul  Bengaluru              2    2500
3         103  Priya    Chennai              4    3200
4         105  Arjun  Hyderabad              6    4000

In [19]:
left = pd.merge(
    customers,
    transactions,
    on="CustomerID",
    how="left"
)

print(left)

   CustomerID   Name       City  TransactionID  Amount
0         101   Asha  Hyderabad            1.0  1200.0
1         101   Asha  Hyderabad            3.0   800.0
2         102  Rahul  Bengaluru            2.0  2500.0
3         103  Priya    Chennai            4.0  3200.0
4         104  Kiran     Mumbai            NaN     NaN
5         105  Arjun  Hyderabad            6.0  4000.0

In [20]:
right = pd.merge(
    customers,
    transactions,
    on="CustomerID",
    how="right"
)

print(right)

   CustomerID   Name       City  TransactionID  Amount
0         101   Asha  Hyderabad              1    1200
1         102  Rahul  Bengaluru              2    2500
2         101   Asha  Hyderabad              3     800
3         103  Priya    Chennai              4    3200
4         106    NaN        NaN              5    1500
5         105  Arjun  Hyderabad              6    4000

In [21]:
outer = pd.merge(
    customers,
    transactions,
    on="CustomerID",
    how="outer",
    indicator=True
)

print(outer)

   CustomerID   Name       City  TransactionID  Amount      _merge
0         101   Asha  Hyderabad            1.0  1200.0        both
1         101   Asha  Hyderabad            3.0   800.0        both
2         102  Rahul  Bengaluru            2.0  2500.0        both
3         103  Priya    Chennai            4.0  3200.0        both
4         104  Kiran     Mumbai            NaN     NaN   left_only
5         105  Arjun  Hyderabad            6.0  4000.0        both
6         106    NaN        NaN            5.0  1500.0  right_only

In [22]:
print(customers["CustomerID"].is_unique)
print(transactions["CustomerID"].is_unique)

True
False

In [23]:
result = customers.merge(
    transactions,
    on="CustomerID",
    how="left",
    validate="one_to_many"
)

print(result)

   CustomerID   Name       City  TransactionID  Amount
0         101   Asha  Hyderabad            1.0  1200.0
1         101   Asha  Hyderabad            3.0   800.0
2         102  Rahul  Bengaluru            2.0  2500.0
3         103  Priya    Chennai            4.0  3200.0
4         104  Kiran     Mumbai            NaN     NaN
5         105  Arjun  Hyderabad            6.0  4000.0

In [24]:
jan = pd.DataFrame({
    "CustomerID": [101, 102],
    "Amount": [1200, 2500]
})

feb = pd.DataFrame({
    "CustomerID": [103, 104],
    "Amount": [1800, 3200]
})

combined = pd.concat([jan, feb], ignore_index=True)

print(combined)

   CustomerID  Amount
0         101    1200
1         102    2500
2         103    1800
3         104    3200

In [25]:
names = pd.DataFrame({
    "Name": ["Asha", "Rahul", "Priya"]
})

scores = pd.DataFrame({
    "Score": [85, 92, 78]
})

combined = pd.concat([names, scores], axis=1)

print(combined)

    Name  Score
0   Asha     85
1  Rahul     92
2  Priya     78

In [26]:
customer_indexed = customers.set_index("CustomerID")
transactions_indexed = transactions.set_index("CustomerID")

result = customer_indexed.join(
    transactions_indexed,
    how="left"
)

print(result)

             Name       City  TransactionID  Amount
CustomerID
101          Asha  Hyderabad            1.0  1200.0
101          Asha  Hyderabad            3.0   800.0
102         Rahul  Bengaluru            2.0  2500.0
103         Priya    Chennai            4.0  3200.0
104         Kiran     Mumbai            NaN     NaN
105         Arjun  Hyderabad            6.0  4000.0

In [27]:
# Attach customer details to every transaction
purchase_data = transactions.merge(
    customers,
    on="CustomerID",
    how="left",
    validate="many_to_one",
    indicator=True
)

print(purchase_data)

   TransactionID  CustomerID  Amount   Name       City     _merge
0              1         101    1200   Asha  Hyderabad       both
1              2         102    2500  Rahul  Bengaluru       both
2              3         101     800   Asha  Hyderabad       both
3              4         103    3200  Priya    Chennai       both
4              5         106    1500    NaN        NaN  left_only
5              6         105    4000  Arjun  Hyderabad       both

In [28]:
unmatched = purchase_data[
    purchase_data["_merge"] == "left_only"
]

print(unmatched)

   TransactionID  CustomerID  Amount Name City     _merge
4              5         106    1500  NaN  NaN  left_only

In [30]:
customer_summary = (
    purchase_data[purchase_data["_merge"] == "both"]
    .groupby(["CustomerID", "Name", "City"], as_index=False)
    .agg(
        Total_Spending=("Amount", "sum"),
        Number_Of_Transactions=("TransactionID", "count"),
        Average_Purchase=("Amount", "mean")
    )
)

(customer_summary.sort_values("Total_Spending", ascending=False))

,CustomerID,Name,City,Total_Spending,Number_Of_Transactions,Average_Purchase
3,105,Arjun,Hyderabad,4000,1,4000.0
2,103,Priya,Chennai,3200,1,3200.0
1,102,Rahul,Bengaluru,2500,1,2500.0
0,101,Asha,Hyderabad,2000,2,1000.0